# Review of the Evidence and Summary of the Main Issues

A comprehensive review of the different uses of HCES is provided in Smith et al. (2014). Among those uses are poverty measurement, informing food security assessment, providing inputs in the compilation of food balance sheets, providing information for the planning and monitoring of nutrition interventions, informing the compilation of national accounts, and collecting data for compilation of CPI. As a result of the different uses, and the constituencies of users associated with them, the demands from the data vary, and depending on the exact nature of HCES being designed, there are going to be different sets of constraints and opportunities for repurposing. Any attempt at adjusting the design of a survey needs to take into account the analytical needs of the different users. In this document, the main uses considered in setting the criteria for guiding survey design are food security assessments, poverty measurement, and nutrition policy and programming.

Some key issues in the measurement of poverty and food security, and for monitoring nutrition interventions, that are useful for understanding the data needs connected to those uses are presented in the Annex 1.^[See Annex 1.] In what follows, the document contains a summary of the literature on key choices that confront practitioners as they design and implement HCES questionnaires. Those aspects were identified as priority areas in a review conducted by Smith et al. (2014) and by experts that participated in the consultation process convened by the IAEG-AG and led by FAO and the World Bank. Several of those issues are also treated, theoretically and empirically, in a recent issue of the journal Food Policy. The volume includes case studies from a diverse set of developing and OECD countries, analyzing how different survey design options affect the quality of the data being collected and, in turn, the implications for statistical inference and policy analysis (Zezza et al., 2017).

## Recall Versus Diary and Length of Reference Period

Data on household food consumption (and acquisition) is commonly collected either by asking households to keep a diary over a reference period (e.g. days or weeks) or through interviews in which respondents are asked to recall consumption for a specific period (e.g. the past week or the past 30 days). A large body of evidence from research and practical experience shows that the method chosen can significantly affect the resulting estimates of consumption.

The _recall period_ is referred to as the period over which respondents are asked to recall the consumption of food items. The recall period differs from the _reference period_ when households are interviewed multiple times during multiple visits to the household Smith et al., (2014). For example, if households are interviewed about their food consumption in the last seven days over four weekly visits, the recall period is seven days and the reference period is 28 days.

In diary methods, households are generally asked to record consumption at the moment in which it takes place (e.g. at meal times or at time of purchase). However, in practice, households often fill in information about their consumption at the end of the day, or during supervised visits from enumerators (for example, for two-day recall periods if visited every other day). This blurs the line between diary and recall methods, especially when respondent illiteracy is high and supervisors support completion of the diary with visits every few days.

...and so forth...

## Seasonality, number of visits

Consumption and expenditure patterns often show seasonal variations that are linked to the agricultural production season, cyclical events, such as floods and droughts, or cultural events (e.g. Ramadan, Christmas), which affect food availability, prices and customary consumption practices. The existence of seasonality in food consumption patterns is well-established (Paxson 1992, 1993; Alderman, 1996) but its extent depends greatly on the context.

Seasonality can be particularly important for food consumption because seasonal variations in dietary patterns, overall quantities of food consumed, and the consumption of particular nutrients can be pronounced, partly because of its relationship with food production cycles (Coates et al., 2012). D’Souza and Jolliffe (2012) find that household consumption in Afghanistan can be as much as one third lower in the lean season compared with the post-harvest season. The different levels of consumption, if taken at face value, would result in estimates of the poverty headcount doubling from 23 percent in the fall to 46 in the following summer (D’Souza and Jolliffe, 2012). Seasonality in food prices is a key concern as it is found to be significant and can affect estimates of poverty and consumption (Gilbert et al., 2016). That is of course a major issue for surveys collecting data for the calculation of CPI.

Seasonal variations can also originate from increased expenditure during festivals and holidays. In the United States, it has been established that consumption is higher during holidays and summer months (Barsky and Miron, 1988). In low- and middle-income countries, expenditure can vary significantly with holidays, festivals, and religious observances. Jolliffe and Serajuddin (2015), using data for Jordan, note that during the period of Ramadan, consumption levels are 11 percent greater than during other periods of the year. The festive expenditures can be difficult to capture in surveys because it is often difficult for survey fieldwork to operate as normal during festive periods. A few surveys, such as the Living Standards Surveys in Viet Nam, use a special recall module for food consumption during festive periods, with analysis typically then spread over the consumption estimates for the households observed in the rest of the year.